branches:
  only:
  - main

environment:
  matrix:
  - job_name: Windows and Linux build
    appveyor_build_worker_image: Ubuntu
  
matrix:
  fast_finish: true


for:
  -
    matrix:
      only:
        - job_name: Windows and Linux build

    install:
    - sh: sudo apt-get update && sudo apt-get install -y libgtk-3-dev g++-mingw-w64-x86-64

    build_script:
        - sh:  cd /home/appveyor/projects/librelancer
        - sh: git submodule update --init --recursive
        - sh:  ./build.sh -j$(nproc) LinuxDaily --with-win64

    test: off
      
    artifacts:
      - path: packaging/packages/librelancer-daily-ubuntu-amd64.tar.gz
        name: librelancer-daily-ubuntu-amd64.tar.gz
      - path: packaging/packages/librelancer-sdk-daily-ubuntu-amd64.tar.gz
        name: librelancer-sdk-daily-ubuntu-amd64.tar.gz
      - path: packaging/packages/librelancer-daily-win64.zip
        name: librelancer-daily-win64.zip
      - path: packaging/packages/librelancer-sdk-daily-win64.zip
        name: librelancer-sdk-daily-win64.zip


    deploy:
      provider: Webhook
      url: https://librelancer.net/webhook.php
      authorization:
        secure: 9aQ2qeWQBx1XSedh23m7NfucPR+NYHeIn4CZDBZSQnxYfrNmQYoAdHkjGwp6Bka46vcaqiq5yYqsMY/YIlaZkviGxsJh5HY9b2vrfHYPpOI=
      request_timeout: 5
